### PR TITLE
 Get package versions at runtime, leverage Docker volumes to improve file cache reuse to speed up runtime

### PR DESCRIPTION
**Pull request by raman325**
Instead of having to update this repo for new releases, this version finds the latest version of the three source packages (wireguard, wireguard-tools, and libnml) at build time and allows for using a cache for the environment build packages to avoid all of the problems that occur with downloading from SourceForge. Also updated to use the latest Ubuntu LTM to avoid future maintenance.

I'm working on a bash script that can be run on a Synology NAS to auto-build the latest version of WireGuard and install/upgrade WireGuard to your NAS. These are intermediary steps to get there.

Assuming you are OK with the file changes, I took a stab at updating the README but feel free to update to suit your needs

### CODE REVIEW

**Comment by runfalk** [comment]
Looks really good. Will try it out later.

**Comment by raman325** [comment]
👍 you can see the script here if you are interested: https://github.com/raman325/syno-wg-autoinstaller

**Comment by raman325** [comment]
Just an FYI, I ran my script using this branch and was able to successfully upgrade to `v1.0.20200712` of the client

**Comment by cristiangauma** [comment]
@runfalk could you try it?. It would be awesome to merge this if it worked as expected as it would be much easier to maintain/update Wireguard on Synology :D.

**Comment by raman325** [comment]
@cristiangauma in the interim, you can use the script in the repo linked above to upgrade WG on your Synology using the instructions in the README

**Comment by runfalk** [comment]
So I've finally taken the time to review and test it. I like it and will merge it. Thank you so much for taking the time to do this @raman325.

**Pull request merged**
