### PR TITLE
Confirm DS218+ with 7.0

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by mkowalski** [comment]
Cross-built on x86_64 with Fedora 34 using the following

```
$ git clone https://github.com/runfalk/synology-wireguard.git
$ cd synology-wireguard
$ mkdir toolkit_tarballs
$ mkdir artifacts
$ sudo docker build -t synobuild .
$ sudo docker run --rm --privileged --env PACKAGE_ARCH=apollolake --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk synobuild
```

**Comment by JonyBCN** [comment]
It has worked for me. I'm using it with WeeJeWel's wg-easy image with no problem. While compiling I had issues with certificates, fixed by adding --no-check-certificate to wget in Makefile calls.

**Comment by namedlock** [comment]
> It has worked for me. I'm using it with WeeJeWel's wg-easy image with no problem. While compiling I had issues with certificates, fixed by adding --no-check-certificate to wget in Makefile calls.

also built successfully for me on Mac OS, and installed successfully on my DSM 918+. 
after manually started with 'sudo /var/packages/WireGuard/scripts/start' , the terminal print out such message
'WireGuard has been successfully started'

**Comment by yllekz** [comment]
> Cross-built on x86_64 with Fedora 34 using the following
> 
> ```
> $ git clone https://github.com/runfalk/synology-wireguard.git
> $ cd synology-wireguard
> $ mkdir toolkit_tarballs
> $ mkdir artifacts
> $ sudo docker build -t synobuild .
> $ sudo docker run --rm --privileged --env PACKAGE_ARCH=apollolake --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk -v $(pwd)/toolkit_tarballs:/toolkit_tarballs synobuild
> ```
> 
> Installed via the Synology UI. Started via SSH with `sudo /var/packages/WireGuard/scripts/start`. Wireguard interfaces go up correctly and provide a working connectivity
> 
> ```
> # /usr/local/bin/wg-quick up wg0
> [#] ip link add wg0 type wireguard
> [#] wg setconf wg0 /dev/fd/63
> [#] ip -4 address add 10.4.0.4/32 dev wg0
> [#] ip link set mtu 1420 up dev wg0
> [#] ip -4 route add 10.4.0.0/24 dev wg0
> 
> # ping 10.4.0.1 -c 1
> PING 10.4.0.1 (10.4.0.1) 56(84) bytes of data.
> 64 bytes from 10.4.0.1: icmp_seq=1 ttl=64 time=51.3 ms
> ```

Confused about this - does this produce an install file? Do you run this on a different system then import it?

**Pull request merged**
